#!/usr/bin/env bash
set -euo pipefail

: "${GAOKUN_DIR:?missing GAOKUN_DIR}"
: "${WORKDIR:?missing WORKDIR}"
: "${ARTIFACT_DIR:?missing ARTIFACT_DIR}"
: "${KERNEL_TAG:?missing KERNEL_TAG}"
: "${PACKAGE_RELEASE_TAG:?missing PACKAGE_RELEASE_TAG}"

BUILD_EL2="${BUILD_EL2:-false}"
KERN_SRC_BASE="${KERN_SRC_BASE:-${KERN_SRC:-}}"
KERN_OUT="${KERN_OUT:-}"
KERN_SRC_EL2="${KERN_SRC_EL2:-${KERN_SRC:-}}"
KERN_OUT_EL2="${KERN_OUT_EL2:-}"

: "${KERN_SRC_BASE:?missing KERN_SRC_BASE}"
: "${KERN_OUT:?missing KERN_OUT}"

BASE_KREL="$(cat "$WORKDIR/kernel-release.txt")"
EL2_KREL=""
if [[ -f "$WORKDIR/kernel-release-el2.txt" ]]; then
  EL2_KREL="$(cat "$WORKDIR/kernel-release-el2.txt")"
fi

PKG_TOPDIR="$WORKDIR/pkgbuild"
BUILDROOT_DIR="$WORKDIR/package-buildroots"
PACMAN_ARCH="${PACMAN_ARCH:-aarch64}"
FIRMWARE_PKGVER="${FIRMWARE_PKGVER:-$(date -u +%Y%m%d)}"
BUILD_TIME_UTC="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

mkdir -p "$ARTIFACT_DIR" "$PKG_TOPDIR"

pkgver_from_krel() {
  local krel="$1"
  krel="${krel//-/_}"
  krel="${krel//[^A-Za-z0-9._+]/_}"
  printf '%s' "$krel"
}

write_pkginfo() {
  local stage_dir="$1"
  local pkg_name="$2"
  local pkgver="$3"
  local pkgdesc="$4"
  shift 4

  {
    printf '# Generated by linux-gaokun-buildbot\n'
    printf 'pkgname = %s\n' "$pkg_name"
    printf 'pkgbase = %s\n' "$pkg_name"
    printf 'pkgver = %s-1\n' "$pkgver"
    printf 'pkgdesc = %s\n' "$pkgdesc"
    printf 'url = https://github.com/KawaiiHachimi/linux-gaokun-buildbot\n'
    printf 'builddate = %s\n' "$(date -u +%s)"
    printf 'packager = github-actions[bot]\n'
    printf 'size = %s\n' "$(du -sb "$stage_dir" | awk '{print $1}')"
    printf 'arch = %s\n' "$PACMAN_ARCH"
    printf 'license = GPL-2.0-only\n'
    while [[ $# -gt 0 ]]; do
      printf '%s\n' "$1"
      shift
    done
  } > "$stage_dir/.PKGINFO"
}

build_pkg() {
  local stage_dir="$1"
  local pkg_name="$2"
  local pkgver="$3"
  local pkg_file="${pkg_name}-${pkgver}-1-${PACMAN_ARCH}.pkg.tar.zst"

  tar --sort=name --zstd --owner=0 --group=0 --numeric-owner \
    -C "$stage_dir" -cf "$PKG_TOPDIR/$pkg_file" .
  cp "$PKG_TOPDIR/$pkg_file" "$ARTIFACT_DIR/$pkg_file"
  printf '%s' "$pkg_file"
}

build_kernel_variant() {
  local variant_key="$1"
  local pkg_suffix="$2"
  local src_dir="$3"
  local out_dir="$4"
  local krel="$5"
  local dtb_name="$6"

  local pkgver
  pkgver="$(pkgver_from_krel "$krel")"

  local kernel_pkg="linux-gaokun3${pkg_suffix}"
  local headers_pkg="linux-gaokun3${pkg_suffix}-headers"
  local kernel_stage="$BUILDROOT_DIR/${kernel_pkg}"
  local modules_raw_stage="$BUILDROOT_DIR/${kernel_pkg}-raw"
  local headers_stage="$BUILDROOT_DIR/${headers_pkg}"
  local headers_tree="$headers_stage/usr/src/${headers_pkg}"

  rm -rf "$kernel_stage" "$modules_raw_stage" "$headers_stage"
  mkdir -p \
    "$kernel_stage/boot/dtbs/${kernel_pkg}/qcom" \
    "$kernel_stage/usr/lib/modules" \
    "$headers_tree" \
    "$headers_stage/usr/lib/modules/$krel"

  install -Dm644 "$out_dir/arch/arm64/boot/Image" \
    "$kernel_stage/boot/vmlinuz-${kernel_pkg}"
  install -Dm644 "$out_dir/System.map" \
    "$kernel_stage/boot/System.map-${kernel_pkg}"
  install -Dm644 "$out_dir/.config" \
    "$kernel_stage/boot/config-${kernel_pkg}"
  install -Dm644 "$out_dir/arch/arm64/boot/dts/qcom/$dtb_name" \
    "$kernel_stage/boot/dtbs/${kernel_pkg}/qcom/$dtb_name"

  make -C "$src_dir" O="$out_dir" ARCH=arm64 INSTALL_MOD_PATH="$modules_raw_stage" modules_install
  mv "$modules_raw_stage/lib/modules/$krel" "$kernel_stage/usr/lib/modules/"
  rm -rf "$modules_raw_stage"
  rm -f "$kernel_stage/usr/lib/modules/$krel/build" \
        "$kernel_stage/usr/lib/modules/$krel/source"
  ln -s "../../../src/${headers_pkg}" "$kernel_stage/usr/lib/modules/$krel/build"
  ln -s "../../../src/${headers_pkg}" "$kernel_stage/usr/lib/modules/$krel/source"
  depmod -b "$kernel_stage" -a "$krel"

  rsync -a --delete --exclude '.git' "$src_dir/" "$headers_tree/"
  rsync -a "$out_dir/" "$headers_tree/"
  find "$headers_tree" -type f \
    \( -name '*.o' -o -name '*.ko' -o -name '*.a' -o -name '*.cmd' -o -name '*.mod' -o -name '*.mod.c' \) \
    -delete
  find "$headers_tree" -type l \( -name build -o -name source \) -delete
  ln -s "../../../src/${headers_pkg}" "$headers_stage/usr/lib/modules/$krel/build"
  ln -s "../../../src/${headers_pkg}" "$headers_stage/usr/lib/modules/$krel/source"

  write_pkginfo "$kernel_stage" "$kernel_pkg" "$pkgver" \
    "Gaokun3 Linux kernel and modules (${krel})" \
    "depend = linux-firmware-gaokun3" \
    "provides = linux=${pkgver}"
  write_pkginfo "$headers_stage" "$headers_pkg" "$pkgver" \
    "Gaokun3 Linux kernel headers (${krel})" \
    "depend = ${kernel_pkg}=${pkgver}-1"

  local kernel_pkg_file
  local headers_pkg_file
  kernel_pkg_file="$(build_pkg "$kernel_stage" "$kernel_pkg" "$pkgver")"
  headers_pkg_file="$(build_pkg "$headers_stage" "$headers_pkg" "$pkgver")"

  printf -v "KREL_${variant_key^^}" '%s' "$krel"
  printf -v "KERNEL_PKG_${variant_key^^}" '%s' "$kernel_pkg_file"
  printf -v "HEADERS_PKG_${variant_key^^}" '%s' "$headers_pkg_file"
}

build_firmware_package() {
  local firmware_stage="$BUILDROOT_DIR/linux-firmware-gaokun3"
  local firmware_pkg

  rm -rf "$firmware_stage"
  mkdir -p "$firmware_stage/usr/lib/firmware"
  cp -a "$GAOKUN_DIR/firmware/." "$firmware_stage/usr/lib/firmware/"

  write_pkginfo "$firmware_stage" "linux-firmware-gaokun3" "$FIRMWARE_PKGVER" \
    "Firmware bundle for Huawei MateBook E Go 2023 (gaokun3)" \
    "provides = linux-firmware-qcom" \
    "provides = linux-firmware-atheros"

  firmware_pkg="$(build_pkg "$firmware_stage" "linux-firmware-gaokun3" "$FIRMWARE_PKGVER")"
  FIRMWARE_PKG="$firmware_pkg"
}

build_kernel_variant "standard" "" "$KERN_SRC_BASE" "$KERN_OUT" "$BASE_KREL" \
  "sc8280xp-huawei-gaokun3.dtb"

if [[ "$BUILD_EL2" == "true" ]]; then
  : "${KERN_OUT_EL2:?missing KERN_OUT_EL2}"
  if [[ -z "$EL2_KREL" ]]; then
    echo "BUILD_EL2=true but kernel-release-el2.txt is missing" >&2
    exit 1
  fi

  build_kernel_variant "el2" "-el2" "$KERN_SRC_EL2" "$KERN_OUT_EL2" "$EL2_KREL" \
    "sc8280xp-huawei-gaokun3-el2.dtb"
fi

build_firmware_package

EL2_MANIFEST_BLOCK=""
EL2_RELEASE_BLOCK=""
if [[ "$BUILD_EL2" == "true" ]]; then
  EL2_MANIFEST_BLOCK="$(cat <<EOF
,
    "el2": {
      "release": "${KREL_EL2}",
      "packages": {
        "kernel": "${KERNEL_PKG_EL2}",
        "headers": "${HEADERS_PKG_EL2}"
      }
    }
EOF
)"
  EL2_RELEASE_BLOCK="$(cat <<EOF
- \`${KERNEL_PKG_EL2}\`
- \`${HEADERS_PKG_EL2}\`
EOF
)"
fi

cat >"$ARTIFACT_DIR/package-manifest.json" <<EOF
{
  "package_release_tag": "${PACKAGE_RELEASE_TAG}",
  "kernel_tag": "${KERNEL_TAG}",
  "build_el2": ${BUILD_EL2},
  "built_at_utc": "${BUILD_TIME_UTC}",
  "firmware_version": "${FIRMWARE_PKGVER}",
  "kernels": {
    "standard": {
      "release": "${KREL_STANDARD}",
      "packages": {
        "kernel": "${KERNEL_PKG_STANDARD}",
        "headers": "${HEADERS_PKG_STANDARD}"
      }
    }${EL2_MANIFEST_BLOCK}
  },
  "packages": {
    "firmware": "${FIRMWARE_PKG}"
  }
}
EOF

cat >"$ARTIFACT_DIR/package-release-body.md" <<EOF
## Package Bundle

- Package Tag: \`${PACKAGE_RELEASE_TAG}\`
- Kernel Tag: \`${KERNEL_TAG}\`
- EL2 Package Set Included: \`${BUILD_EL2}\`
- Firmware Version: \`${FIRMWARE_PKGVER}\`
- Architecture: \`${PACMAN_ARCH}\`
- Build Time (UTC): \`${BUILD_TIME_UTC}\`

## Included Pacman Packages

- \`${KERNEL_PKG_STANDARD}\`
- \`${HEADERS_PKG_STANDARD}\`
${EL2_RELEASE_BLOCK}
- \`${FIRMWARE_PKG}\`
EOF
